name: Run Test Message Agregation on Main Merge

on:
  push:
    branches:
      - main  

jobs:
  run_script:
    runs-on: ubuntu-latest

    env:
      TG_API_ID: ${{ secrets.TG_API_ID }}
      TG_API_HASH: ${{ secrets.TG_API_HASH }}
      TG_SESSION_STRING: ${{ secrets.TG_SESSION_STRING }}
      GPT_API_KEY: ${{ secrets.GPT_API_KEY }}
      CHANNEL_NAME: "me"  # Replace with the actual channel name
      DAYS_TO_PARSE: '2'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Node.js script
        run: node start
